### ISSUE TITLE
Extension needs to be updated for Inkscape 1.0

### ISSUE THREAD

**Issue by fyrak1s** [sonejostudios/InkscapePreviewLayer#1]
Hey with the current version of Inkscape I'm getting
```
  File "preview_layer.py", line 34
    def draw_SVG_square(self, (w,h), (x,y), parent):
                              ^
SyntaxError: invalid syntax

```
It might need to be updated against [Inkscape 1.0 extensions API](https://wiki.inkscape.org/wiki/index.php?title=Updating_your_Extension_for_1.0).

**Comment by sonejostudios** [comment]
Hi @Nuc1eoN ,

You are completely right, the script needs to be updated to the new version API. Due of a lack of time, I can't do it right now...

Actually I was hopping there will be a "preview" function in Inkscape 1.0, which would make this script obsolete. Still because of (no) time, I couldn't try the 1.0 for now..  So I ask you:

Do you know if there is a "preview" possibility (show only whats on the page) in Inkscape 1.0?

**Comment by fyrak1s** [comment]
> Do you know if there is a "preview" possibility (show only whats on the page) in Inkscape 1.0?

Hey @sonejostudios, unfortunately not that I am aware of. I am currently on the latest 1.0 release and found your plugin exactly because I needed that functionality.

I would even be fine with a checkbox like "Don't draw over canvas".

But since I could not find it I must assume this functionality is not there.


EDIT:
Personally I think the best way would be to have this option under the 'View' menu entry, between entries like "Split Vue Mode" and "Page Grid".

However I dont know if that is possible to implement with an extension.

**Comment by sonejostudios** [comment]
Hi @Nuc1eoN ,

I totally agree, a menu entry in the View menu of Inkscape would be the best. Actually, I still don't know why they don't add this really simple function, which seems to me to be essential... especially if the user do print stuff and wants to have a look to the final product without exporting it.

Okay, I'll have a look these days asap to the script. Maybe it's not a big deal at all. Just need to take the time.
AFAIK it is not possible to add menu entries with extensions, so it will remain in the extension menu (but who know what 1.0 API ca do?) we'll see.

**Comment by sonejostudios** [comment]
Hi @Nuc1eoN ,

I tried to adapt it to 1.0 but unfortunately I didn't succeed. It look more like I need to rewrite it completely. 

Maybe, instead, we should add a feature request to the devs... because to me it feels like a must have feature instead of an extension, what do you think?

**Comment by fyrak1s** [comment]
Hey @sonejostudios sorry for the late response.

Yes I would agree that it is a pretty important feature. I don't really see why this wasn't implemented yet :P

**Comment by sonejostudios** [comment]
Hi @Nuc1eoN ,

I just added a feature request to Inkscape:

https://gitlab.com/inkscape/inbox/-/issues/3191

Have a nice day!

**Comment by sonejostudios** [comment]
Hi @Nuc1eoN ,

just to let you know, I just released the new version of the extension for Inkscape 1.x ! :)

All the best

**Comment by fyrak1s** [comment]
Thank you!
